### PR TITLE
PEP8, simplified parts, use with open()...

### PR DESCRIPTION
**Pull request by HerrMuellerluedenscheid**
Hey @jasbur,

Great tool!

I restyled a couple of lines to stick a little more to the PEP8 rules. There are still a couple of lines to work on but it's a start. I also replaced a couple of file openings with the `with` functions and removed a few uncalled `close` calls on files.

Best regards

### CODE REVIEW

**Comment by jasbur** [comment]
I got a chance to read through the changes and they all look like great improvements to my messy code :) One question though; is it unnecessary to call a `.close` when a file is opened with `with open()`? I see you removed them.

**Comment by HerrMuellerluedenscheid** [comment]
I'm glad you like them:)

Opening files using `with` will call `close` at the end of the scope
automagically. So, no need to do that manually. It's also a little saver in
case of an exception happening within the open scope.

Jason Burgett <notifications@github.com> schrieb am So., 7. Okt. 2018,
01:42:

**Comment by jasbur** [comment]
Excellent, I didn't know that. I'm just going to test everything out on an actual Pi and merge this if everything works.

**Comment by HerrMuellerluedenscheid** [comment]
Just realized that I messed up with installation paths. I'll reopen this PR as soon as I resolved things. How about adding a setup.py using setuptools? That should make the installation a little smoother.

**Pull request closed without merging**
